// Generated by scripts/build.mjs. Edit core.mjs, music.mjs and app.mjs instead.
(() => {
"use strict";
const KEY = 'kegel_helper_v1';
const dateKey = (d = new Date()) => `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;
const object = v => v && typeof v === 'object' && !Array.isArray(v) ? v : {};
const integer = (v, fallback, min, max) => Number.isFinite(v) ? Math.max(min, Math.min(max, Math.floor(v))) : fallback;
function normalize(raw, now = new Date()) {
  const s = {...object(raw)};
  s.version = 5;
  s.kegelTarget = integer(s.kegelTarget, 3, 1, 10);
  s.holdSec = integer(s.holdSec, 3, 2, 10);
  s.restSec = integer(s.restSec, Math.max(6, s.holdSec), s.holdSec, 20);
  s.kegelGroups = integer(s.kegelGroups, 0, 0, 10000);
  s.totalGroups = integer(s.totalGroups, 0, 0, 1000000);
  s.checkins = {...object(s.checkins)};
  s.records = {...object(s.records)};
  s.planStart = /^\d{4}-\d{1,2}-\d{1,2}$/.test(s.planStart || '') ? s.planStart : dateKey(now);
  s.sound = s.sound === true;
  s.music = s.music === true;
  s.musicVolume = integer(s.musicVolume, 35, 0, 100);
  s.trainingMode = s.trainingMode === 'auto' ? 'auto' : 'hold';
  s.theme = ['light','dark','system'].includes(s.theme) ? s.theme : 'system';
  s.completedSessions = Array.isArray(s.completedSessions) ? s.completedSessions.filter(id=>typeof id==='string').slice(-100) : [];
  s.pendingSession = Session.restore(s.pendingSession)?.snapshot() || null;
  if(s.pendingSession && s.completedSessions.includes(s.pendingSession.id))s.pendingSession=null;
  if(s.day && s.kegelGroups > 0 && !s.records[s.day]) s.records[s.day] = {groups:s.kegelGroups};
  if(s.day !== dateKey(now)) { s.day = dateKey(now); s.kegelGroups = integer(s.records[s.day]?.groups, 0, 0, 10000); }
  return s;
}
function completeGroup(state, seconds, now = new Date(), sessionId = null) {
  const s = normalize(state, now);
  if(sessionId && s.completedSessions.includes(sessionId))return s;
  s.kegelGroups++; s.totalGroups++;
  const old = object(s.records[s.day]);
  s.records[s.day] = {groups:s.kegelGroups, seconds:integer(old.seconds,0,0,1000000)+Math.round(seconds)};
  if(s.kegelGroups >= s.kegelTarget) s.checkins[s.day] = true;
  if(sessionId){s.completedSessions=[...s.completedSessions,sessionId].slice(-100);if(s.pendingSession?.id===sessionId)s.pendingSession=null;}
  return s;
}
function streak(s, now = new Date()) {
  const d = new Date(now.getFullYear(),now.getMonth(),now.getDate(),12);
  if(!s.checkins[dateKey(d)]) d.setDate(d.getDate()-1);
  let n=0;
  while(s.checkins[dateKey(d)] && n < 100000) {n++;d.setDate(d.getDate()-1);}
  return n;
}
function planDay(s, now = new Date()) {
  const [y,m,d] = s.planStart.split('-').map(Number);
  return Math.max(1,Math.floor((Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())-Date.UTC(y,m-1,d))/86400000)+1);
}
// Clock-independent training state machine; UI supplies monotonic timestamps.
class Session {
  constructor({holdSec=3,restSec=6,reps=10,trainingMode='hold',id}={}) {
    this.holdMs=holdSec*1000; this.restMs=restSec*1000; this.reps=reps;
    this.mode=trainingMode==='auto'?'auto':'hold';
    this.id=id || globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    this.done=0; this.phase='ready'; this.progress=0; this.remaining=holdSec;
    this.startedAt=0; this.pausedFrom=null; this.credited=false; this.afterPrepare='ready';
  }
  begin(phase, now) {this.phase=phase;this.startedAt=now;this.progress=phase==='rest'?1:0;this.remaining=(phase==='prepare'?3000:phase==='rest'?this.restMs:this.holdMs)/1000;}
  prepare(now,next='ready'){this.afterPrepare=next;this.begin('prepare',now);}
  start(now){if(this.mode==='auto')this.prepare(now,'hold');}
  press(now) {if(this.mode==='hold'&&this.phase==='ready') {this.begin('hold',now);return true;}return false;}
  tick(now) {
    if(!['prepare','hold','rest'].includes(this.phase))return;
    const ms=this.phase==='prepare'?3000:this.phase==='hold'?this.holdMs:this.restMs;
    const elapsed=Math.max(0,now-this.startedAt), p=Math.min(1,elapsed/ms);
    this.progress=this.phase==='prepare'?0:this.phase==='rest'?1-p:p;
    this.remaining=Math.max(0,Math.ceil((ms-elapsed)/1000));
    if(p===1) {
      // Never catch up across multiple phases after a delayed frame.
      if(this.phase==='prepare')this.begin(this.afterPrepare,now);
      else if(this.phase==='hold'){
        if(this.mode==='auto'){this.done++;this.begin('rest',now);}else this.phase='release';
      }else if(this.done===this.reps)this.phase='complete';
      else if(this.mode==='auto')this.begin('hold',now);
      else {this.phase='ready';this.remaining=this.holdMs/1000;}
    }
  }
  release(now) {
    if(this.mode==='auto')return null;
    this.tick(now);
    if(this.phase==='hold') {this.phase='ready';this.progress=0;this.remaining=this.holdMs/1000;return 'early';}
    if(this.phase==='release') {this.done++;this.begin('rest',now);return 'rest';}
    return null;
  }
  pause(now) {
    if(['paused','complete'].includes(this.phase))return;
    // Auto mode must never award a repetition when a background event arrives late.
    if(this.mode==='hold')this.tick(now);
    if(this.phase==='complete')return;
    if(this.phase==='release') {this.done++;this.begin('rest',now);}
    this.pausedFrom=this.phase==='rest'?'rest':this.phase==='prepare'&&this.afterPrepare==='rest'?'rest':'ready';
    this.phase='paused';this.progress=0;
  }
  resume(now,withPreparation=false) {
    if(this.phase!=='paused')return;
    if(withPreparation){this.prepare(now,this.pausedFrom==='rest'?'rest':this.mode==='auto'?'hold':'ready');return;}
    if(this.pausedFrom==='rest')this.begin('rest',now);
    else {this.phase='ready';this.progress=0;this.remaining=this.holdMs/1000;}
  }
  snapshot(){
    if(this.phase==='complete'||this.credited)return null;
    const done=this.phase==='release'?this.done+1:this.done;
    const nextPhase=this.phase==='rest'||this.phase==='release'||this.phase==='paused'&&this.pausedFrom==='rest'||this.phase==='prepare'&&this.afterPrepare==='rest'?'rest':'ready';
    return {v:1,id:this.id,mode:this.mode,holdSec:this.holdMs/1000,restSec:this.restMs/1000,reps:this.reps,done,nextPhase};
  }
  static restore(raw){
    if(!raw||raw.v!==1||typeof raw.id!=='string'||!raw.id||raw.id.length>100||!['hold','auto'].includes(raw.mode)||raw.reps!==10)return null;
    if(!Number.isInteger(raw.holdSec)||raw.holdSec<2||raw.holdSec>10||!Number.isInteger(raw.restSec)||raw.restSec<raw.holdSec||raw.restSec>20)return null;
    if(!Number.isInteger(raw.done)||raw.done<0||raw.done>10||!['ready','rest'].includes(raw.nextPhase)||raw.done===10&&raw.nextPhase!=='rest')return null;
    const s=new Session({holdSec:raw.holdSec,restSec:raw.restSec,reps:10,trainingMode:raw.mode,id:raw.id});
    s.done=raw.done;s.phase='paused';s.pausedFrom=raw.nextPhase;return s;
  }
}

// WebKit's default ambient session follows the iPhone silent switch.
// Select the media playback channel before creating/resuming an AudioContext.
function configurePlayback(navigatorLike){
  try{if(navigatorLike?.audioSession){navigatorLike.audioSession.type='playback';return true;}}catch{}
  return false;
}

// Original ambient composition: overlapping warm chords and sparse bell notes.
// All oscillators have whole cycles per loop, including the wrapped envelopes.
function composeAmbient(sampleRate=22050) {
  const duration=24, length=sampleRate*duration;
  const channels=[new Float32Array(length),new Float32Array(length)];
  const chords=[[50,57,61,64],[47,54,57,62],[43,55,59,62],[45,57,59,64]];
  const melody=[74,73,69,66,69,73,71,69];
  const frequency=midi=>Math.round(440*2**((midi-69)/12)*duration)/duration;
  for(let c=0;c<2;c++){
    const out=channels[c];
    chords.forEach((chord,k)=>chord.forEach((note,j)=>{
      const f=frequency(note),phase=c*.24+j*.37;
      for(let i=0;i<length;i++){
        const t=i/sampleRate,age=(t-k*6+duration)%duration;
        if(age>=12)continue;
        const envelope=Math.sin(Math.PI*age/12)**2;
        out[i]+=.045*envelope*(Math.sin(2*Math.PI*f*t+phase)+.12*Math.sin(4*Math.PI*f*t+phase));
      }
    }));
    melody.forEach((note,k)=>{
      const f=frequency(note);
      for(let i=0;i<length;i++){
        const t=i/sampleRate,age=(t-k*3+duration)%duration;
        if(age>=4.5)continue;
        const envelope=(1-Math.exp(-age*5))*Math.exp(-age*1.1)*Math.sin(Math.PI*age/4.5)**2;
        out[i]+=.11*envelope*Math.sin(2*Math.PI*f*t+c*.18);
      }
    });
  }
  return {channels,sampleRate,duration};
}

class AmbientMusic {
  constructor(context){this.context=context;this.buffer=null;this.voice=null;this.voices=new Set();this.offset=0;}
  prepare(){
    if(this.buffer)return;
    const {channels,sampleRate}=composeAmbient();
    this.buffer=this.context.createBuffer(2,channels[0].length,sampleRate);
    channels.forEach((data,c)=>this.buffer.copyToChannel(data,c));
  }
  level(volume){return Math.max(0,Math.min(100,Number(volume)||0))/100*.65;}
  ramp(voice,value,seconds){
    const t=this.context.currentTime,p=voice.gain.gain;
    // Preserve the instantaneous value when reversing an unfinished fade.
    const a=voice.automation;
    const current=a ? a.from+(a.to-a.from)*Math.min(1,Math.max(0,(t-a.at)/a.seconds)) : 0;
    p.cancelScheduledValues(t);p.setValueAtTime(current,t);p.linearRampToValueAtTime(value,t+seconds);
    voice.automation={from:current,to:value,at:t,seconds};
  }
  start(volume){
    if(this.context.state!=='running')return false;
    if(this.voice)return true;
    this.prepare();
    const source=this.context.createBufferSource(),gain=this.context.createGain();
    const voice={source,gain,at:this.context.currentTime,offset:this.offset};
    source.buffer=this.buffer;source.loop=true;source.connect(gain);gain.connect(this.context.destination);
    gain.gain.setValueAtTime(0,this.context.currentTime);
    this.voice=voice;this.voices.add(voice);
    source.onended=()=>{source.disconnect();gain.disconnect();this.voices.delete(voice);};
    source.start(0,this.offset);this.ramp(voice,this.level(volume),.8);return true;
  }
  setVolume(volume){if(this.voice)this.ramp(this.voice,this.level(volume),.2);}
  stop({immediate=false,reset=false}={}){
    if(this.voice){
      this.offset=(this.voice.offset+this.context.currentTime-this.voice.at)%this.buffer.duration;
      const voice=this.voice;this.voice=null;
      this.ramp(voice,0,immediate?.015:.4);
      voice.source.stop(this.context.currentTime+(immediate?.02:.45));
    }
    if(immediate)for(const voice of this.voices){voice.gain.gain.cancelScheduledValues(this.context.currentTime);voice.gain.gain.setValueAtTime(0,this.context.currentTime);voice.source.stop(this.context.currentTime);}
    if(reset)this.offset=0;
  }
}

const $ = id => document.getElementById(id);
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const setText = (id,value) => {const el=$(id),s=String(value);if(el.textContent!==s)el.textContent=s;};
let storageBlocked=false, S;
function storageWarning(message){$('storage-warning').hidden=false;setText('storage-warning',message);}
try {
  const raw=localStorage.getItem(KEY);
  S=normalize(raw?JSON.parse(raw):{});
  if(raw && JSON.parse(raw)?.version!==5 && !localStorage.getItem(KEY+'_pre_v5')) localStorage.setItem(KEY+'_pre_v5',raw);
} catch(error) {
  storageBlocked=true;S=normalize({});
  storageWarning('暂时无法读取原有记录，原始数据未覆盖。请检查浏览器存储设置；当前可体验练习。');
}
function save(){
  if(storageBlocked)return false;
  try{localStorage.setItem(KEY,JSON.stringify(S));$('storage-warning').hidden=true;return true;}
  catch{storageWarning('记录暂未保存：浏览器存储不可用或空间不足。关闭页面后本次进度可能丢失。');return false;}
}
save();
let currentPage='home',guideReturn='home',session=null,frameId=0,pointerId=null,keyHeld=null;
let calendarDate=new Date();calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1);
let lastPhase='',lastDone=-1,toastTimer,audioContext,wakeLock=null,wakePending=false,lastFrameTime=0,lastCheckpoint='';
let ambientMusic=null,musicPreview=false,musicPreviewTimer=null;
let swRegistration=null,updatePending=false,hadController=!!navigator.serviceWorker?.controller,reloading=false;
const knownPages=['home','records','settings','guide','exercise','complete'];
const systemTheme=matchMedia('(prefers-color-scheme: dark)');
function applyTheme(){
  const dark=S.theme==='dark'||S.theme==='system'&&systemTheme.matches;
  document.documentElement.dataset.theme=dark?'dark':'light';
  document.querySelector('meta[name="theme-color"]').content=dark?'#19251f':'#f6f5f0';
  document.querySelectorAll('button[data-theme]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.theme===S.theme)));
}
systemTheme.addEventListener('change',applyTheme);
document.querySelectorAll('button[data-theme]').forEach(el=>el.addEventListener('click',()=>{S.theme=el.dataset.theme;applyTheme();save();}));
document.querySelectorAll('[data-mode]').forEach(el=>el.addEventListener('click',()=>{S.trainingMode=el.dataset.mode;save();render();}));

function toast(message){setText('toast',message);$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function rollover(){if(S.day!==dateKey()){S=normalize(S);save();}}
function markTarget(){if(S.kegelGroups>=S.kegelTarget)S.checkins[S.day]=true;}
function displayDate(key){const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d,12);}
function shortDate(key){const d=displayDate(key);return `${d.getMonth()+1}月${d.getDate()}日`;}
function render(){
  rollover();
  const now=new Date(),percent=Math.min(100,Math.round(S.kegelGroups/S.kegelTarget*100));
  setText('today-date',`${now.getMonth()+1}月${now.getDate()}日 · 星期${'日一二三四五六'[now.getDay()]}`);
  setText('home-done',S.kegelGroups);setText('home-target',S.kegelTarget);setText('daily-percent',`${percent}%`);
  $('daily-ring').style.strokeDashoffset=100-percent;
  setText('home-status',percent>=100?'今日目标已完成':'慢慢来，也很好');
  const seconds=(S.holdSec+S.restSec)*10,min=Math.floor(seconds/60),sec=seconds%60;
  setText('duration',`约 ${min?min+' 分':''}${sec?' '+sec+' 秒':''}`.trim());
  setText('hold-meta',`收紧 ${S.holdSec} 秒`);
  // Keep the icon in the start button stable when its label changes.
  $('start').firstChild.textContent=S.pendingSession?'继续上次练习 ':percent>=100?'今日已达标 ':S.trainingMode==='auto'?'开始自动引导 ':'开始训练 ';
  setText('streak',streak(S));setText('total-days',Object.values(S.checkins).filter(Boolean).length);setText('total-groups',S.totalGroups);
  setText('setting-target',S.kegelTarget);setText('setting-hold',S.holdSec);setText('setting-rest',S.restSec);
  setText('plan-day',`陪伴你的第 ${planDay(S)} 天 · 每组 10 次`);
  document.querySelectorAll('[data-adjust]').forEach(button=>{
    const [key,delta]=button.dataset.adjust.split(':'),n=Number(delta);
    const bounds=key==='kegelTarget'?[1,10]:key==='holdSec'?[2,10]:[S.holdSec,20];
    button.disabled=S[key]+n<bounds[0]||S[key]+n>bounds[1];
  });
  document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.mode===S.trainingMode)));
  setText('mode-help',S.trainingMode==='auto'?'准备 3 秒后自动切换，无需持续按住':'按住收紧，提示后松开放松');
  const draft=S.pendingSession;$('resume-card').hidden=!draft;$('hero-restart').hidden=!draft;
  $('home').classList.toggle('has-resume',!!draft);
  for(const id of ['session-meta','mode-picker','mode-help'])$(id).hidden=!!draft;
  $('start').setAttribute('aria-describedby',draft?'resume-title resume-details resume-next':'mode-help');
  if(draft){
    setText('resume-title',draft.done===10?'还差最后一次放松':`本组已完成 ${draft.done}/10 次`);
    setText('resume-details',`${draft.mode==='auto'?'自动引导':'按住训练'} · 收紧 ${draft.holdSec} 秒 / 放松 ${draft.restSec} 秒`);
    setText('resume-next',draft.nextPhase==='rest'?'准备 3 秒后，先完成放松。':'准备 3 秒后，从这一次重新开始。');
  }
  applyTheme();renderSound();renderMusic();renderWeek();renderCalendar();renderRecent();
}
function renderSound(){
  $('sound-toggle').setAttribute('aria-checked',String(S.sound));
  $('exercise-sound').setAttribute('aria-pressed',String(S.sound));
  $('exercise-sound').setAttribute('aria-label',S.sound?'关闭提示音':'开启提示音');
  $('exercise-sound').querySelector('use').setAttribute('href',S.sound?'#i-sound':'#i-mute');
  if(session)renderExerciseFootnote();
}
function renderExerciseFootnote(){
  setText('exercise-footnote',session?.mode==='auto'?(S.sound?'高音收紧，低音放松。离开页面会自动暂停。':'跟随屏幕节奏。离开页面会自动暂停。'):'进度自动保存，退出后也可以继续。');
}
function dayStatus(key){return S.checkins[key]?'done':S.records[key]?.groups>0?'partial':'';}
function renderWeek(){
  const now=new Date(),monday=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12);
  monday.setDate(monday.getDate()-(monday.getDay()+6)%7);
  const fragment=document.createDocumentFragment();let practiced=0;
  for(let i=0;i<7;i++){
    const d=new Date(monday);d.setDate(d.getDate()+i);const key=dateKey(d),status=dayStatus(key);
    if(status)practiced++;
    const cell=document.createElement('div');cell.className=`week-day ${status} ${key===dateKey()?'today':''}`;
    cell.setAttribute('aria-label',`${shortDate(key)}${key===dateKey()?'，今天':''}，${status==='done'?'已达标':status?'有练习':'未记录'}`);
    const label=document.createElement('span');label.textContent='一二三四五六日'[i];cell.append(label);
    const disc=document.createElement('span');disc.className='day-disc';
    if(status==='done')disc.innerHTML=icon('check');else disc.textContent=d.getDate();
    cell.append(disc);fragment.append(cell);
  }
  $('week-strip').replaceChildren(fragment);
  setText('week-note',practiced?`这周已经练习 ${practiced} 天，每一点坚持都算数。`:'不用着急，今天就是很好的开始。');
  setText('weekly-days',practiced);$('weekly-progress').style.width=`${practiced/7*100}%`;
  setText('weekly-summary-note',practiced?'不必追赶别人，\n保持自己的节奏。':'从今天开始，\n留下一点进步。');
}
function renderCalendar(){
  const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),lead=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();
  setText('calendar-title',`${y} 年 ${m+1} 月`);
  const total=Math.ceil((lead+days)/7)*7,fragment=document.createDocumentFragment();
  for(let i=0;i<total;i++){
    const d=new Date(y,m,i-lead+1,12),key=dateKey(d),inMonth=d.getMonth()===m,status=inMonth?dayStatus(key):'';
    const cell=document.createElement('span');cell.className=`calendar-cell ${!inMonth?'dim':status} ${key===dateKey()?'today':''}`;
    cell.textContent=d.getDate();cell.setAttribute('aria-label',`${shortDate(key)}${key===dateKey()?'，今天':''}，${status==='done'?'已达标':status?'有练习':'未记录'}`);fragment.append(cell);
  }
  $('calendar-grid').replaceChildren(fragment);
}
function renderRecent(){
  const keys=[...new Set([...Object.keys(S.records).filter(k=>S.records[k]?.groups>0),...Object.keys(S.checkins).filter(k=>S.checkins[k])])].filter(k=>/^\d{4}-\d{1,2}-\d{1,2}$/.test(k)).sort((a,b)=>displayDate(b)-displayDate(a)).slice(0,5);
  if(!keys.length){$('recent-records').innerHTML='<div class="empty-records"><strong>第一份记录，等你开启</strong>完成一组练习后，会自动记录在这里。</div>';return;}
  const fragment=document.createDocumentFragment();
  keys.forEach(key=>{
    const row=document.createElement('div');row.className='recent-row';const text=document.createElement('div');
    text.textContent=key===dateKey()?'今天':shortDate(key);
    const sub=document.createElement('small'),groups=S.records[key]?.groups;
    sub.textContent=groups?`完成 ${groups} 组 · ${groups*10} 次`:'历史达标记录';text.append(sub);
    const badge=document.createElement('span');badge.className='tag';badge.textContent=S.checkins[key]?'目标达成':'已留下进步';row.append(text,badge);fragment.append(row);
  });$('recent-records').replaceChildren(fragment);
}
function route(page,push=true){
  if(!knownPages.includes(page))page='home';
  if(page==='guide')guideReturn=currentPage==='settings'?'settings':'home';
  document.querySelectorAll('.page').forEach(el=>{const active=el.id===page;el.hidden=!active;el.classList.toggle('active',active);});
  document.querySelectorAll('.tab').forEach(el=>{const active=el.dataset.page===page;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});
  document.body.classList.toggle('focus-mode',['exercise','guide','complete'].includes(page));
  currentPage=page;if(page!=='settings')stopMusicPreview();window.scrollTo({top:0,behavior:'instant'});
  if(push)history.pushState({page},'');
  if(page!=='exercise')releaseWakeLock();
  if(['home','settings','records'].includes(page))render();
  const heading=$(page).querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}
  safeUpdate();
}
history.replaceState({page:'home'},'');
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>route(button.dataset.page)));
window.addEventListener('popstate',ev=>{
  let target=ev.state?.page||'home';if(['exercise','complete'].includes(target))target='home';
  if(session&&currentPage==='exercise'){
    pauseSession();
    abandonSession();
  }
  route(target,false);
});
$('guide-back').addEventListener('click',()=>route(guideReturn));
document.querySelectorAll('[data-adjust]').forEach(button=>button.addEventListener('click',()=>{
  rollover();const [key,delta]=button.dataset.adjust.split(':');S[key]+=Number(delta);S=normalize(S);markTarget();save();render();
}));
function musicWanted(){return !document.hidden&&(musicPreview&&currentPage==='settings'||S.music&&session&&currentPage==='exercise'&&!['paused','complete'].includes(session.phase));}
function stopMusicPreview(){if(!musicPreview)return;musicPreview=false;clearTimeout(musicPreviewTimer);syncMusic();}
function renderMusic(){
  $('music-toggle').setAttribute('aria-checked',String(S.music));
  $('exercise-music').setAttribute('aria-pressed',String(S.music));
  $('exercise-music').setAttribute('aria-label',S.music?'关闭背景音乐':'开启背景音乐');
  $('music-volume').value=S.musicVolume;
  setText('music-volume-value',`${S.musicVolume}%`);
  setText('music-preview',musicPreview?'停止试听':'试听音乐 · 8 秒');
  $('music-preview').setAttribute('aria-pressed',String(musicPreview));
  const playing=!!ambientMusic?.voice&&audioContext?.state==='running';
  $('exercise-music').dataset.playing=String(playing);
  setText('exercise-music-label',!S.music?'音乐已关':session?.phase==='paused'?'音乐已暂停':S.musicVolume===0?'音乐音量为零':playing?'微光 · 播放中':'音乐待播放');
}
function syncMusic(){
  try{if(musicWanted()&&audioContext?.state==='running'){ambientMusic??=new AmbientMusic(audioContext);ambientMusic.start(S.musicVolume);}
  else ambientMusic?.stop({immediate:document.hidden,reset:!session});}catch{toast('音乐暂时无法播放，试试重新开启');}
  renderMusic();
}
async function unlockAudio(){
  if(!S.sound&&!S.music&&!musicPreview)return;
  configurePlayback(navigator);
  try{
    if(!audioContext){
      audioContext=new (window.AudioContext||window.webkitAudioContext)();
      audioContext.addEventListener('statechange',()=>{
        if(audioContext.state!=='running'){ambientMusic?.stop({immediate:true});stopMusicPreview();if(session)pauseSession();renderMusic();}
      });
    }
    if(audioContext.state!=='running')await audioContext.resume();
    // Recheck current intent after resume: a pause/exit may have happened meanwhile.
    syncMusic();
  }catch{toast('声音暂时无法开启，请再点一次声音开关');}
}
function toggleMusic(){
  S.music=!S.music;save();syncMusic();
  if(S.music){unlockAudio();toast(session?'背景音乐已开启':'已开启「微光」，开始练习时播放');}
  else toast('背景音乐已关闭');
}
$('music-preview').addEventListener('click',()=>{
  if(musicPreview){stopMusicPreview();return;}
  if(S.musicVolume===0){toast('请先调高音乐音量，再试听');return;}
  musicPreview=true;renderMusic();unlockAudio();
  musicPreviewTimer=setTimeout(stopMusicPreview,8000);
});
$('music-toggle').addEventListener('click',toggleMusic);
$('exercise-music').addEventListener('click',toggleMusic);
$('music-volume').addEventListener('input',()=>{S.musicVolume=Number($('music-volume').value);ambientMusic?.setVolume(S.musicVolume);renderMusic();});
$('music-volume').addEventListener('change',save);
function tone(frequency=660){
  if(!S.sound||!audioContext||audioContext.state!=='running')return;
  try{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;
    oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency,t);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.045,t+.015);gain.gain.exponentialRampToValueAtTime(.001,t+.18);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t);oscillator.stop(t+.2);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};
  }catch{}
}
function toggleSound(){S.sound=!S.sound;save();renderSound();unlockAudio();toast(S.sound?'轻提示音已开启':'提示音已关闭');}
$('sound-toggle').addEventListener('click',toggleSound);$('exercise-sound').addEventListener('click',toggleSound);
async function requestWakeLock(){
  if(wakeLock||wakePending||!navigator.wakeLock||document.hidden||currentPage!=='exercise'||session?.phase==='paused')return;
  wakePending=true;
  try{const lock=await navigator.wakeLock.request('screen');if(currentPage!=='exercise'||session?.phase==='paused'||document.hidden){await lock.release();return;}wakeLock=lock;lock.addEventListener('release',()=>{if(wakeLock===lock)wakeLock=null;});}catch{}finally{wakePending=false;}
}
function releaseWakeLock(){if(wakeLock){const lock=wakeLock;wakeLock=null;lock.release().catch(()=>{});}}
function checkpoint(){
  if(!session||session.phase==='complete')return;
  const draft=session.snapshot(),signature=JSON.stringify(draft);
  if(signature===lastCheckpoint)return;
  S.pendingSession=draft;
  if(save())lastCheckpoint=signature;
}
function startSession(restore=false){
  rollover();session=restore?Session.restore(S.pendingSession):new Session(S);
  if(!session){S.pendingSession=null;save();render();return;}
  if(restore)session.resume(performance.now(),true);else session.start(performance.now());
  lastPhase='';lastDone=-1;lastCheckpoint='';pointerId=null;keyHeld=null;lastFrameTime=performance.now();
  route('exercise');unlockAudio();requestWakeLock();drawSession();scheduleFrame();
}
async function requestStart(){
  rollover();
  if(S.pendingSession){startSession(true);return;}
  if(S.kegelGroups>=S.kegelTarget){if(!await showDialog('今天的目标已经完成','可以收下今天的进步，好好放松。如果你正按专业指导增加练习，也可以继续。','再练一组','今天先到这里'))return;}
  startSession();
}
$('start').addEventListener('click',requestStart);$('guide-start').addEventListener('click',requestStart);
async function restartSession(){
  const rhythm=`${S.trainingMode==='auto'?'自动引导':'按住训练'} · 收紧 ${S.holdSec} 秒 / 放松 ${S.restSec} 秒`;
  if(!await showDialog('重新开始这一组？',`将放弃本组进度，按当前设置从第 1 次开始：\n${rhythm}\n\n历史记录会保留。`,'重新开始','保留进度'))return;
  S.pendingSession=null;save();requestStart();
}
$('hero-restart').addEventListener('click',restartSession);
function scheduleFrame(){if(!frameId&&session&&['prepare','hold','rest'].includes(session.phase)){if(!lastFrameTime)lastFrameTime=performance.now();frameId=requestAnimationFrame(frame);}}
function frame(now){
  frameId=0;if(!session)return;
  if(session.mode==='auto'&&now-lastFrameTime>2000){pauseSession();toast('练习已暂停，准备好再继续');return;}
  lastFrameTime=now;session.tick(now);drawSession();scheduleFrame();
}
function stopFrame(){cancelAnimationFrame(frameId);frameId=0;}
function drawSession(){
  if(!session)return;
  const {phase,done}=session;
  $('training-progress').style.strokeDashoffset=100-session.progress*100;
  setText('phase-time',phase==='paused'?'—':phase==='release'?'✓':session.remaining);
  if(lastDone!==done){
    $('rep-dots').innerHTML=Array.from({length:10},(_,i)=>`<i class="${i<done?'done':i===done?'current':''}"></i>`).join('');
    $('rep-dots').setAttribute('aria-label',`已完成 ${done} 次`);
    lastDone=done;
  }
  const finishingRest=phase==='rest'||phase==='paused'&&session.pausedFrom==='rest'||phase==='prepare'&&session.afterPrepare==='rest';
  setText('rep-number',Math.min(10,finishingRest?done:done+1));
  if(phase===lastPhase)return;
  const previous=lastPhase;lastPhase=phase;
  syncMusic();
  checkpoint();
  $('training-stage').dataset.phase=phase;
  $('training-stage').dataset.mode=session.mode;
  setText('exercise-mode',session.mode==='auto'?'自动引导 · 无需持续按住':'按住训练 · 跟随自己的节奏');
  const titles={prepare:'先放松，准备好',ready:done?'继续下一次':'准备好了吗',hold:'轻轻收紧',release:'可以松开了',rest:'慢慢放松',paused:'歇一小会儿',complete:'这一组完成了'};
  const subtitles={prepare:session.afterPrepare==='rest'?'接下来先完成放松，再继续':'给自己 3 秒，调整到舒服的姿势',ready:'按住蜜桃，轻轻收紧盆底肌',hold:'保持这个力度，记得自然呼吸',release:'松开手指，让肌肉完全放松',rest:done===10?'完成最后一次放松，就结束这一组':'不着急，给身体充分放松的时间',paused:'已完成的次数会保留，继续时先放松',complete:'放松一下，收下今天的进步'};
  if(phase==='paused')subtitles.paused=session.pausedFrom==='rest'?'已完成的次数会保留，继续后先完成放松':'已完成的次数会保留，继续后重做这一次';
  setText('phase-title',titles[phase]);setText('phase-subtitle',subtitles[phase]);
  setText('timer-unit',phase==='prepare'?'秒准备':phase==='rest'?'秒放松':phase==='release'?'请松手':phase==='paused'?'已暂停':'秒收紧');
  setText('breath-note',phase==='paused'?'继续前会有 3 秒准备时间':'自然呼吸，腹部与臀部保持放松');
  $('hold-button').setAttribute('aria-pressed',String(session.mode==='hold'&&['hold','release'].includes(phase)));
  $('hold-button').setAttribute('aria-disabled',String(session.mode==='auto'||['prepare','paused','rest','complete'].includes(phase)));
  $('hold-button').setAttribute('aria-label',session.mode==='auto'?'自动引导进行中，请跟随文字与进度环':'按住开始收紧，提示后松开放松');
  $('hold-button').tabIndex=session.mode==='auto'?-1:0;
  renderExerciseFootnote();
  $('pause').querySelector('use').setAttribute('href',phase==='paused'?'#i-play':'#i-pause');
  $('pause').querySelector('span').textContent=phase==='paused'?'继续练习':'暂停练习';
  const step=phase==='hold'||phase==='ready'?'hold':phase==='rest'||phase==='release'?'rest':null;
  document.querySelectorAll('[data-step]').forEach(el=>{
    const active=el.dataset.step===step;el.classList.toggle('current',active);
    if(active)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');
  });
  if(phase==='release'||phase==='rest'&&session.mode==='auto')tone(440);
  if(phase==='hold'&&session.mode==='auto'||phase==='ready'&&previous==='rest')tone(740);
  if(phase==='complete')finishSession();
}
function press(){if(!session||session.mode!=='hold'||session.phase!=='ready')return false;unlockAudio();session.press(performance.now());lastFrameTime=performance.now();drawSession();scheduleFrame();return true;}
function release(){if(!session)return;const result=session.release(performance.now());if(result==='early')toast('先放松一下，准备好再试这一次');drawSession();scheduleFrame();}
const holdButton=$('hold-button');
holdButton.addEventListener('pointerdown',ev=>{
  if(ev.button!==0||pointerId!==null||keyHeld!==null)return;ev.preventDefault();
  if(press()){pointerId=ev.pointerId;holdButton.setPointerCapture(ev.pointerId);}
});
holdButton.addEventListener('pointerup',ev=>{
  if(ev.pointerId!==pointerId)return;ev.preventDefault();pointerId=null;
  if(holdButton.hasPointerCapture(ev.pointerId))holdButton.releasePointerCapture(ev.pointerId);release();
});
holdButton.addEventListener('pointercancel',ev=>{if(ev.pointerId===pointerId){pointerId=null;pauseSession();}});
holdButton.addEventListener('lostpointercapture',ev=>{if(ev.pointerId===pointerId){pointerId=null;pauseSession();}});
holdButton.addEventListener('contextmenu',ev=>ev.preventDefault());
holdButton.addEventListener('keydown',ev=>{if(![' ','Enter'].includes(ev.key))return;ev.preventDefault();if(!ev.repeat&&keyHeld===null&&pointerId===null&&press())keyHeld=ev.key;});
window.addEventListener('keyup',ev=>{if(keyHeld===ev.key){ev.preventDefault();keyHeld=null;release();}});
holdButton.addEventListener('blur',()=>{if(keyHeld!==null){keyHeld=null;pauseSession();}});
function pauseSession(){
  if(!session||session.phase==='complete')return;
  pointerId=null;keyHeld=null;session.pause(performance.now());lastFrameTime=0;stopFrame();releaseWakeLock();drawSession();
}
$('pause').addEventListener('click',()=>{
  if(!session)return;
  if(session.phase==='paused'){session.resume(performance.now(),true);lastFrameTime=performance.now();unlockAudio();requestWakeLock();drawSession();scheduleFrame();}
  else pauseSession();
});
function abandonSession(){stopFrame();session=null;pointerId=null;keyHeld=null;releaseWakeLock();syncMusic();}
$('exit-training').addEventListener('click',()=>{
  if(!session)return;
  pauseSession();
  abandonSession();route('home');
});
function finishSession(){
  if(!session||session.credited)return;
  session.credited=true;const seconds=(session.holdMs+session.restMs)/1000*session.reps;
  // Read the last committed state before counting; the session ID prevents replay.
  if(!storageBlocked){try{const raw=localStorage.getItem(KEY);if(raw)S=normalize(JSON.parse(raw));}catch{}}
  S=completeGroup(S,seconds,new Date(),session.id);save();tone(880);
  setText('complete-time',`${seconds}秒`);setText('complete-groups',`${S.kegelGroups}/${S.kegelTarget}`);
  setText('complete-subtitle',session.mode==='auto'?'这一组引导已完成，放松一下。':S.kegelGroups>=S.kegelTarget?'今日目标已达成，现在可以好好放松。':'放松一下，让身体记住这份从容。');
  abandonSession();history.replaceState({page:'complete'},'');route('complete',false);
}
document.addEventListener('visibilitychange',()=>{
  if(document.hidden){stopMusicPreview();if(session)pauseSession();releaseWakeLock();}
  else {render();swRegistration?.update().catch(()=>{});safeUpdate();}
});
window.addEventListener('pagehide',()=>{stopMusicPreview();if(session)pauseSession();releaseWakeLock();});
window.addEventListener('storage',ev=>{
  if(ev.key!==KEY)return;
  try{const incoming=normalize(ev.newValue?JSON.parse(ev.newValue):{}),active=!!session;abandonSession();S=incoming;if(active){route('home');toast('练习状态已在另一页面更新，请从一个页面继续');}else render();}catch{}
});
setInterval(()=>{if(S.day!==dateKey())render();},15000);
let modalResolve=null,modalFocus=null;
function showDialog(title,body,confirm='知道了',cancel=''){
  if(modalResolve)return Promise.resolve(false);
  setText('dialog-title',title);setText('dialog-body',body);setText('dialog-confirm',confirm);setText('dialog-cancel',cancel);
  $('dialog-cancel').hidden=!cancel;modalFocus=document.activeElement;
  $('dialog').setAttribute('aria-labelledby','dialog-title');$('dialog').setAttribute('aria-describedby','dialog-body');$('dialog').showModal();
  // Prefer the non-destructive action in confirmation dialogs.
  (cancel?$('dialog-cancel'):$('dialog-confirm')).focus();
  return new Promise(resolve=>{modalResolve=resolve;});
}
function closeDialog(value){$('dialog').close();const resolve=modalResolve;modalResolve=null;modalFocus?.focus({preventScroll:true});resolve?.(value);}
$('dialog-confirm').addEventListener('click',()=>closeDialog(true));$('dialog-cancel').addEventListener('click',()=>closeDialog(false));
$('dialog').addEventListener('cancel',ev=>{ev.preventDefault();closeDialog(false);});
$('install-help').addEventListener('click',()=>showDialog('把练习放在主屏幕','1. 用 iPhone 的 Safari 打开这个网址。\n2. 点分享按钮，选择「添加到主屏幕」。\n3. 添加后，从主屏幕图标打开。\n\n首次联网打开后，练习页面可离线使用。'));
$('reset-data').addEventListener('click',async()=>{
  if(!await showDialog('清空练习记录？','当前设备的打卡记录、累计组数与未完成练习将被清空，无法撤销。你的练习节奏和外观设置会保留。','清空记录','保留记录'))return;
  const next=normalize({kegelTarget:S.kegelTarget,holdSec:S.holdSec,restSec:S.restSec,sound:S.sound,music:S.music,musicVolume:S.musicVolume,trainingMode:S.trainingMode,theme:S.theme});
  try{localStorage.removeItem(KEY+'_pre_v5');localStorage.setItem(KEY,JSON.stringify(next));S=next;storageBlocked=false;render();$('storage-warning').hidden=true;toast('记录已清空，随时可以重新开始');}catch{toast('未能清空记录，请检查浏览器存储设置');}
});
$('prev-month').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar();});
$('next-month').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar();});
// Activate a downloaded update only between sessions, preserving an ongoing set.
function safeUpdate(){
  if(session||currentPage==='complete'||$('dialog').open)return;
  if(swRegistration?.waiting)swRegistration.waiting.postMessage({type:'SKIP_WAITING'});
  if(updatePending&&!reloading){reloading=true;location.reload();}
}
if('serviceWorker' in navigator && ['http:','https:'].includes(location.protocol)){
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(!hadController){hadController=true;return;}
    updatePending=true;safeUpdate();
  });
  window.addEventListener('load',()=>{
    navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{
      swRegistration=reg;reg.update().catch(()=>{});safeUpdate();
      reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed')safeUpdate();});});
    }).catch(()=>{});
  });
}
render();

})();
