import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const core=await readFile(new URL('core.mjs',root),'utf8');
const app=await readFile(new URL('app.mjs',root),'utf8');
const body=app.replace(/^import \{[^\n]+\} from '\.\/core\.mjs';\r?\n/,'');
if(body===app||/^import\s/m.test(body))throw new Error('Unexpected app imports; update the standalone builder.');
const bundle='// Generated by scripts/build.mjs. Edit core.mjs and app.mjs instead.\n'+
  '(() => {\n"use strict";\n'+core.replace(/^export /gm,'')+'\n'+body+'\n})();\n';
const target=new URL('app.js',root);
if(process.argv.includes('--check')){
  const existing=await readFile(target,'utf8');
  if(existing.replace(/\r\n/g,'\n')!==bundle.replace(/\r\n/g,'\n'))throw new Error('app.js is stale. Run npm run build.');
  console.log('Standalone bundle is up to date.');
}else{await writeFile(target,bundle);console.log('Built app.js for both file:// and HTTPS.');}
